export type ExceptionType =
  | "DuplicateControllerException"
  | "DuplicateHandlerException"
  | "DuplicateRouterException"
  | "HyperException"
  | "NotRoleException"
  | "NotScopeException"
  | "MethodNotFountException"
  | "DuplicateControllerPathException"
  | "DuplicateHandlerException"
  | "DuplicatedException"
  | "NotPropertyException"
  | "WrongPlaceException"
  | "HyperFileException"
  | "DpublicateModuleException";
